name: GlowNightLight
main: com.moosemanstudios.GlowNightLight.GlowNightLight
version: 1.0
commands:
    gnl:
        description: Toggles NightLight ability on and off
permissions:
    glownightlight.nl:
        description: Toggles NightLight ability on and off
    glownightlight.reload:
        description: Reloads the config
    glownightlight.time:
        description: sets time