name: ${name}
version: ${project.version}
description: ${description}
author: moose517
main: com.moosemanstudios.GlowNightLight.Bukkit.GlowNightLight
commands:
    gnl:
        description: Geneal GlowNightLight command
permissions:
    glownightlight.nl:
        description: Toggles NightLight ability on and off
    glownightlight.admin:
        description: Allows for admin features
    glownightlight.*:
        description: All permission nodes
        children:
            glownightlight.nl: true
            glownightlight.admin: true